# Generated by Django 2.0.7 on 2018-08-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('receive', 'Receive'), ('change', 'Change')], max_length=10)),
                ('relpath', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=500)),
                ('block_height', models.IntegerField()),
                ('block_hash', models.CharField(max_length=500)),
                ('block_time', models.DateTimeField()),
                ('raw', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Xpub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('xpub', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='xpub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Xpub'),
        ),
        migrations.AddField(
            model_name='balancechange',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Transaction'),
        ),
        migrations.AddField(
            model_name='balancechange',
            name='xpub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Xpub'),
        ),
        migrations.AddField(
            model_name='address',
            name='xpub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Xpub'),
        ),
    ]
