# Generated by Django 2.0.7 on 2018-08-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_processedblock_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpub',
            name='xpub',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='xpub',
            unique_together={('xpub', 'network')},
        ),
    ]
