# Generated by Django 2.0.7 on 2018-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180827_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
