# Generated by Django 2.0.7 on 2018-09-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_erc20token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='erc20_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.ERC20Token'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_erc20_token_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
