# Generated by Django 2.0.7 on 2018-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180927_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=50),
        )
    ]
