# Generated by Django 2.0.7 on 2018-09-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20180927_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erc20token',
            name='contract_address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='processedblock',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('ETH', 'ETH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='xpub',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('ETH', 'ETH')], max_length=100),
        ),
    ]
