# Generated by Django 2.0.7 on 2019-01-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20181106_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_erc20_fee',
            field=models.BooleanField(default=False),
        ),
    ]
