# Generated by Django 2.0.7 on 2019-02-14 19:02

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_chainheight'),
    ]

    operations = [
        migrations.RunSQL(
            """
             CREATE INDEX lower_case_address ON tracker_address (lower(address));
            """
        )
    ]
