# Generated by Django 2.0.7 on 2019-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_tracker_totals_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpub',
            name='script_type',
            field=models.CharField(choices=[('eth', 'eth'), ('p2pkh', 'p2pkh'), ('p2sh-p2wpkh', 'p2sh-p2wpkh')], null=True, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='xpub',
            unique_together={('xpub', 'network', 'script_type')},
        ),
        migrations.RunSQL(
            """
            UPDATE tracker_xpub
            set script_type = 'eth'
            where
            network = 'ETH';
            """
        ),
        migrations.RunSQL(
            """
            UPDATE tracker_xpub
            set script_type = 'p2pkh'
            where
            network != 'ETH';
            """
        ),
        migrations.AlterField(
            model_name='xpub',
            name='script_type',
            field=models.CharField(choices=[('eth', 'eth'), ('p2pkh', 'p2pkh'), ('p2sh-p2wpkh', 'p2sh-p2wpkh')], null=False, max_length=16)
        ),
    ]
