# Generated by Django 2.0.7 on 2019-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_segwit_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpub',
            name='sync_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('SYNCING', 'SYNCING'), ('FAILED', 'FAILED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=16),
        ),
    ]
