# Generated by Django 2.0.7 on 2019-07-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_xpub_sync_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'xpub')},
        ),
    ]
