# Generated by Django 2.0.7 on 2019-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_auto_20190718_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedblock',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('DGB', 'DGB'), ('ETH', 'ETH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='xpub',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('DGB', 'DGB'), ('ETH', 'ETH')], max_length=100),
        ),
    ]
