# Generated by Django 2.0.7 on 2019-06-18 i8:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20190729_1451'),
    ]

    operations = [
        migrations.RenameModel('Xpub', 'Account')
    ]
