# Generated by hand by keepkeyjon

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_rename_xpub_to_account'),
    ]

    operations = [
        migrations.RenameField('Address', 'xpub', 'account'),
        migrations.RenameField('Transaction', 'xpub', 'account'),
        migrations.RenameField('BalanceChange', 'xpub', 'account')
    ]
