# Generated by Django 2.0.7 on 2019-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_xpub_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=78),
        ),
    ]
