# Generated by Django 2.0.7 on 2020-04-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_auto_20200326_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('DGB', 'DGB'), ('ETH', 'ETH'), ('ATOM', 'ATOM'), ('BNB', 'BNB'), ('XRP', 'XRP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('DGB', 'DGB'), ('ETH', 'ETH'), ('ATOM', 'ATOM'), ('BNB', 'BNB'), ('XRP', 'XRP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='processedblock',
            name='network',
            field=models.CharField(choices=[('BTC', 'BTC'), ('BCH', 'BCH'), ('LTC', 'LTC'), ('DOGE', 'DOGE'), ('DASH', 'DASH'), ('DGB', 'DGB'), ('ETH', 'ETH'), ('ATOM', 'ATOM'), ('BNB', 'BNB'), ('XRP', 'XRP')], max_length=100),
        ),
    ]
