# Generated by Django 2.0.7 on 2020-04-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20200429_1312'),
    ]

    operations = [

        # gusd
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0x056fd409e1d7a124bd7017459dfea2f387b6d5cd'));
            """
        ),
        # ht
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0x6f259637dcd74c767781e37bc6133cd6a68aa161'));
            """
        ),
        # husd
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0xdf574c24545e5ffecb9a659c229253d4111d87e1'));
            """
        ),
        # knc
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0xdd974d5c2e2928dea5f71b9825b8b646686bd200'));
            """
        ),
        # link
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0x514910771af9ca656af840dff83e8264ecf986ca'));
            """
        ),
        # paxg
        migrations.RunSQL(
            """
                update tracker_erc20token
                set supported = true
                where lower(contract_address) in (
                lower('0x45804880de22913dafe09f4980848ece6ecbaf78'));
            """
        )
    ]
