# Generated by Django 2.0.7 on 2021-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0044_auto_20210301_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
    ]
