# Generated by Django 2.0.7 on 2021-02-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0045_account_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
